spring:
  application:
    name: one-day-worker-service-registry

server:
  port: 8080

eureka:
  client:
    register-with-eureka: false   # Don't register the registry itself
    fetch-registry: false         # Don't fetch services, it is the registry
  instance:
    hostname: localhost

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
